### ISSUE TITLE
ClientStorer api and example lead to duplicate cookie bugs

### ISSUE THREAD

**Issue by jmhodges** [volatiletech/authboss#155] opened 2017-09-17 17:51 UTC
Because ClientStorer has only a Put with no Save method (like gorilla/sessions has), authboss makes user code write the cookies it uses to the response headers immediately and can be called multiple times for multiple flash lookups or session writes.

This, in the examples given and in the obvious code, will causes duplicate Set-Cookie headers to be written with different contents but the same name.

This will cause bugs because the first cookie written will likely be the one the browser uses. This seems to be a pretty serious API problem.

**Comment by jack-chung** [comment] 2017-09-19 16:48
I have seen this behavior in my app for sure, but I haven't noticed actual bugs caused by this. I haven't performed extensive browser testing, but the few that my team has used are taking the last cookie value.


It's definitely desirable to improve the API so there's just one Set-Cookie.


________________________________

**Comment by aarondl** [comment] 2017-10-01 17:41
@jmhodges What version of Go is this using? Sorry for the late response, been out of the country.

**Comment by aarondl** [comment] 2018-03-05 22:46
@jmhodges This should be solved in v2 where we now only ever call the `WriteToHeader()` kind of method one time at the end of the request (just before the headers themselves are written out).

This is the API here:
https://github.com/volatiletech/authboss/blob/9ef2a06dcb6a99b2a33817131e506ee3fd695988/client_state.go#L48-L61

It uses this response writer internally which allows this functionality:
https://github.com/volatiletech/authboss/blob/9ef2a06dcb6a99b2a33817131e506ee3fd695988/client_state.go#L79-L91

This should alleviate the concern. Thoughts? I want to make sure this is fixed before I actually write v2.x on a tag somewhere.

**Comment by aarondl** [comment] 2018-05-14 22:13
Should be fixed in v2, we only ever write cookies/sessions once per request now.

**Closed by aarondl** 2018-05-14 22:13 UTC
